cnlohr/ch32fun

README.md
add libusb otherwise minichlink would not build.
=> Update README: add libusb package

examples/adc_polled/Makefile, examples/adc_polled/adc.h, examples/adc_polled/adc_polled.c
This PR adds an example for using the ADC for software polled conversion of a single input channel.
=> Added polled ADC example

examples/adc_polled/Makefile, examples/blink/Makefile, examples/bootload/Makefile, examples/debugprintfdemo/Makefile, examples/external_crystal/Makefile, examples/i2c_oled/Makefile, examples/optionbytes/Makefile, examples/run_from_ram/Makefile, examples/sandbox/Makefile, examples/self_modify_code/Makefile, examples/systick_irq/Makefile, examples/tim1_pwm/Makefile, examples/uartdemo/Makefile, examples/ws2812bdemo/Makefile
An even better fix for Issue #30
=> Better way to handle Windows linking to the right libgcc.a

examples/GPIO/GPIO.c, examples/GPIO/Makefile, examples/GPIO/README.md, examples/GPIO/wiring_digital.c, examples/GPIO/wiring_digital.h
Thank you again for creating this!
=> added GPIO example

examples/GPIO/wiring.c, examples/GPIO/wiring.h, examples/GPIO_analogRead/GPIO_analogRead.c, examples/GPIO_analogRead/Makefile, examples/GPIO_analogRead/README.md, examples/GPIO_analogRead/wiring.c, examples/GPIO_analogRead/wiring.h
hope this is ok..
though I noticed that the ADC input seems to be lagging behind slightly (like a slowly-charging and discharging capacitor), maybe I made an error somewhere.
=> GPIO example expanded by ADC functions, additional ADC example

ch32v003fun/ch32v003fun.mk, examples/build_all.cmd
Minor build improvements:
- #include <stdio.h> moved to ch32v003fun.h
- added build_all.cmd to build all examples
=> Minor build improvements

minichlink/pgm-wch-linke.c
=> old read mode for v307 targets

minichlink/Makefile, minichlink/microgdbstub.h
https://github.com/cnlohr/ch32v003fun/pull/106 without CMake.
=> fix macOS compilation

examples/standby_btn/Makefile, examples/standby_btn/README.md, examples/standby_btn/standby_btn.c
=> standby + button example

examples/standby/Makefile, examples/standby/README.md, examples/standby/standby.c
Marek M did the groundwork, I spent the day to get it to work.
Hope this is good enough to be pulled.
=> standby + auto-wakeup example

examples/i2c_slave/Makefile, examples/i2c_slave/README.md, examples/i2c_slave/i2c_slave.c, examples/i2c_slave/i2c_slave.h
Should pass CI this time, apparently the main C file and output files should be named the same as the directory containing the example.
=> Add I2C slave library and example

ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.h
добрые друзья,
I'd like to propose some basic interrupt suspension functions.
The intention is to temporarily disable all interrupts except the one you're interested in so it can run un-impeded and with as little delay as possible, without the need for nesting.
I hope this will be useful and is light enough to be part of ch32v003fun.
=> interrupt suspension functions

ch32v003fun/ch32v003fun.h
Value was shifted 4 bits to the right
=> Fix SPI Direction

minichlink/minichlink.c, minichlink/pgm-wch-linke.c
Fixed a few bits for the ch32v307, as discussed on Discord. I have verified ch32v003 support remains operational.
=> Fixes for the ch32v307

README.md, minichlink/ardulink.c, minichlink/minichlink.c, minichlink/minichlink.h
Makes the Unbrick mode operational.
=> Ardulink - control power instead of reset

add_include.py, platformio.ini
=> Fix PIO build for funconfig branch

minichlink/pgm-wch-linke.c
See https://github.com/cnlohr/ch32v003fun/issues/227 for details.
=> Add warning message if WCH-LinkE is detected in ARM mode

examples/standby_autowake/README.md, examples/standby_autowake/standby_autowake.c, examples/standby_btn/README.md, examples/standby_btn/standby_btn.c
Set GPIOs to input pull-up/pull-down is required to achieve 10uA standby current. Update examples and added notes.
=> Update standby examples and add implementation notes.

examples/color_lcd/Makefile, examples/color_lcd/ch32v_hal.h, examples/color_lcd/ch32v_hal.inl, examples/color_lcd/color_lcd.c, examples/color_lcd/funconfig.h, examples/color_lcd/spi_lcd.h, examples/color_lcd/spi_lcd.inl
Please add my color LCD example/library
=> Added ST77xx color LCD example

ch32v003fun/ch32v003fun.h
=> added __isenabled_irq __get_cpu_sp, minor linting

ch32v003fun/ch32v003fun.mk
Add `-fdata-sections` to compile flags - see here:
* https://github.com/cnlohr/ch32v003fun/issues/265
=> Add `-fdata-sections` to compile flags

README.md
Hi !
I am new to this project. When I read the README, I was confused about what NHC-Link042 is. I tried googling it but couldn't find useful information. I believe adding a link to it in the README would better assist newcomers.
=> Add NHC-Link042 url link in README.md

.github/workflows/minichlink.yml
=> Remove macos 11 from the builders.

ch32v003fun/ch32v003fun.h
Context: https://github.com/zephyrproject-rtos/zephyr/pull/73761#issuecomment-2222371157.
=> Add SPDX-License-Identifier line

README.md
=> Fixup README typos, slight addition

README.md
Added a few links to 003fun-related repos to libraries and projects to increase discover-ability.
=> Added some 003fun-related libraries/projects to the README.md

ch32v003fun/ch32v003fun.c
This change allows me to completely toss my libc function internalization hack :+1:
=> Weak linkage for symbols that might conflict with libc

ch32v003fun/ch32v003fun.mk, minichlink/microgdbstub.h, minichlink/minichgdb.c
* On ch32v203, by default, only assume we have 10 kB of RAM, otherwise some people will be very confused.
=>  * Fix GDB for 32-register setups.

ch32v003fun/ch32v003fun.c
Mind double-checking me @hexaedron ?
=> Cleanup (macro algebra) the 30x interrupts.

examples_v30x/debugprintfdemo/Makefile, minichlink/minichlink.c, minichlink/minichlink.h, minichlink/pgm-esp32s2-ch32xx.c, minichlink/pgm-wch-linke.c, misc/README.md
Working RVSWD implementation in software for minichlink + the esp32-s2 programmer
=> Add RVSWD reference implementation to minichlink.

ch32v003fun/ch32v003fun.h
Added missing higher bit for remapping USART1 as per page 60 in RM.
=> Add USART1_REMAP_1

examples_v30x/interrupt_timing_test/Makefile, examples_v30x/interrupt_timing_test/funconfig.h, examples_v30x/interrupt_timing_test/interrupt_timing_test.c
=> Add interrupt test, for testing performance of EXTI interrupts in diferent scenarios

ch32fun/ch32fun.c, examples/adc_fixed_fs/adc_fixed_fs.c, minichlink/minichlink.c
* Fix async poll_input
* Shrink the hardfault handler from about 1.5kB to about 180 bytes.
=> Fix async + Shrink Crash handler

extralibs/ssd1306.h, extralibs/ssd1306_i2c.h, extralibs/ssd1306_i2c_bitbang.h, extralibs/ssd1306_spi.h
Make it possible to customize startup code for OLED displays, and pass through errors.
=> OLED passthrough errors + allow custom startup code.

ch32fun/ch32v003hw.h, ch32fun/ch32v10xhw.h, ch32fun/ch32v20xhw.h, ch32fun/ch32v30xhw.h, ch32fun/ch32x03xhw.h, misc/attic/hardware_header_all_combined.h
=> Fix naming bug in DMA CFGR header for channels 4 to 7

ch32fun/ch32fun.c, ch32fun/ch32fun.h, ch32fun/ch32fun.mk, ch32fun/ch32x00xhw.h
this makes it so x00x projects can be built without v003 shims.
=> Make x00x more intercompatible with v003

examples_v30x/debugprintfdemo/funconfig.h
Fixed a typo in the debugprintfdemo for ch32v30x.
=> Fixed a typo in the debugprintfdemo for ch32v30x.

ch32fun/ch32fun.h, ch32fun/ch32fun.mk, ch32fun/ch32x00xhw.h, examples_x00x/Readme.md, examples_x00x/adc_polled/Makefile, examples_x00x/adc_polled/README.md, examples_x00x/adc_polled/adc_polled.c, examples_x00x/adc_polled/funconfig.h
This is the start of my integration of the complete build system for the CH32x00x chips.  It includes changes to the global .mk and .h files as well as a small enhancement to the x00x specific header file.
=> Fixes for 00x chips to build

ch32fun/README.md, minichlink/minichlink.c, minichlink/pgm-wch-linke.c
Every example from ch32x035 can run smoothly on ch643.
=> minichlink: add ch643

examples/i2c_oled/i2c_oled.c, extralibs/ssd1306.h
Took settings from u8g2 https://github.com/olikraus/U8g2_Arduino/blob/master/src/clib/u8x8_d_ssd1306_72x40.c
=> Add support for 0.42 inch OLED

ch32fun/ch32fun.c, ch32fun/ch32fun.h, ch32fun/ch32fun.ld, ch32fun/ch32fun.mk, ch32fun/ch58xhw.h, examples_ch58x/blink/Makefile, examples_ch58x/blink/blink.c, examples_ch58x/blink/funconfig.h, examples_ch58x/debugprintfdemo/Makefile, examples_ch58x/debugprintfdemo/debugprintfdemo.c, examples_ch58x/debugprintfdemo/funconfig.h, examples_ch59x/RTC_irq/funconfig.h, examples_ch59x/debugprintfdemo/funconfig.h, examples_ch59x/lowpower/funconfig.h, examples_ch59x/systick_irq/funconfig.h, examples_ch59x/uartdemo/funconfig.h
The same porting procedure as for CH59x was used, which was also applied and working for CH573.
Fully validated on CH582F.
I did not aim for this PR number, I guess it was just meant to be.
=> CH58x bringup and blinky, debugprintf demo

ch32fun/ch32fun.c
Still need to test this and need sign-off by @jjflash65
=> Fix implementation of strchr, ref #583

examples_v30x/rtc/Makefile, examples_v30x/rtc/README.md, examples_v30x/rtc/funconfig.h, examples_v30x/rtc/rtc.c
This example demonstrates how to configure the RTC and set an alarm interrupt.
=> add rtc example

ch32fun/ch32fun.h, minichlink/minichlink.c
allowing it to speed along whnn subsequent data is available.
=> Improve printf by increasing timeout 

examples_usb/README.md, examples_usb/USBFS/README.md, examples_usb/USBFS/usbfs_cdc_uart/99-ch32fun.rules, examples_usb/USBFS/usbfs_cdc_uart/Makefile, examples_usb/USBFS/usbfs_cdc_uart/README.md, examples_usb/USBFS/usbfs_cdc_uart/funconfig.h, examples_usb/USBFS/usbfs_cdc_uart/uart.c, examples_usb/USBFS/usbfs_cdc_uart/uart.h, examples_usb/USBFS/usbfs_cdc_uart/usb_config.h, examples_usb/USBFS/usbfs_cdc_uart/usbfs_cdc_uart.c, extralibs/fsusb.c, extralibs/fsusb.h
I will add more comments to the code and clean up dead parts when I will be adding CH5xx uart code. Also will try to write broader readme after that.
=> Add CDC ACM example, clean

ch32fun/ch32x00xhw.h
I have NOT confirmed that it works fine.
=> Add GPIOB and USART2 based on CH32V00XRM.PDF

examples_v20x/exti_blink/exti_blink.c
I added a function for setting any pin as EXTI trigger. Also expanded comments to better explain what is happening.
Before it was hard for me to understand what I needed to change to use another pin for interrupt.
This also should work on ch32v30x.
=> Improve EXTI blink example for ch32v20x

extralibs/fsusb.c
Fixes #701. PR created for discussion.
=> Only do USB errata workaround for OUT requests

ch32fun/ch32fun.c
=> Make funAnalogInit() work on ch32v208

ch32fun/ch32fun.c, ch32fun/ch32fun.ld
This was already working for ch59x, now also for ch58x.
=> enable high_code RAM area for ch58x
