cnlohr/ch32fun

minichlink/minichlink.c
When using D5 as serial out the chip can not be flashed anymore. For this case there is an option to erase the device. I sniffed the command with usbpcap on windows and added it to minichlink.
Example: The chips is sending data via D5 which stops D1 form working as SDIO:
```
openocd -f ./vendor/wch-riscv.cfg -c init -c halt -c "program ./build/firmware.bin" -c exit
Open On-Chip Debugger 0.11.0+dev-02215-gcc0ecfb6d-dirty (2022-11-05-14:36)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Ready for Remote Connections
Info : WCH-LinkE-CH32V307  mod:RV version 2.8 
Error:  WCH-Link failed to connect with riscvchip
Error:  1.Make sure the two-line debug interface has been opened. If not, set board to …
```
=> Add "Clear all code flash" option to revive "bricked" SOP8's

ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.h
When calling the `SystemInit48HSI()`-function to set the frequency to 48 MHz the` HSITRIM`-Value in `RCC->CTLR` is set to 0 and the clock is running slower than expected. 
The Datasheet states that the setting of the PLL has to be done before setting `PLLON`.
This PR fixes this problem for me and i moved the activation of the PLL one line down.
=> Prevent overwrite of HSITRIM default-value in SystemInit48HSI()

examples/systick_irq/Makefile, examples/systick_irq/systick.h, examples/systick_irq/systick_irq.c
This PR adds an IRQ-based SysTick example that provides a new millisecond delay routine that uses a background 1ms SysTick counter. The new features are provided in a "standard-compliant" single-file-header format.
=> Added SysTick example

platformio.ini
```-DSTDOUT_UART``` is missing in the uartdemo environment for platformio
=> fix platformio uartdemo environment

examples/tim1_pwm/Makefile, examples/tim1_pwm/t1pwm.h, examples/tim1_pwm/tim1_pwm.c
This PR contains an example project that outputs two separate PWM channels on PD0 and PC4 using TIM1 in PWM1 mode.
=> New example demonstrating use of TIM1 for 2 channel PWM output

examples/i2c_oled/.gdbinit, examples/i2c_oled/README.md, examples/i2c_oled/debug.sh, examples/i2c_oled/i2c.h
This PR upgrades the I2C driver to operate with non-blocking IRQ-driven I/O and adds high-speed clocking which has been tested to 800kHz.
=> Add IRQ-driven operation and clocking to 800kHz

examples/MCOtest/MCOtest.c, examples/MCOtest/Makefile, examples/MCOtest/README.md
I wrote a quick example of how to use the MCO function to output one of the internal clock signals to the MCO pin (PC4)
=> Add an example for the MCO function

ch32v003fun/ch32v003fun.c
Added '.option arch, +zicsr\n" ' so that Arch Linux will pull in support for zicsr.
=> Added option so Arch Linux will pull in zicsr support

ch32v003fun/ch32v003fun.c
This PR adds a putchar() function which is required to handle cases where single-character printf() calls are optimized by GCC. It has been tested and confirmed to work with both UART and Debug printing.
=> Add putchar() to fix linker errors when using printf on single character strings

ch32v003fun/ch32v003fun.c
This PR implements putchar() at the lowest level separately for UART and Debug modes as you outlined in our Discord discussion. Although it adds a small amount of extra code it should improve execution time, especially in the Debug case where a lot of dead code paths are eliminated.
=> cnlohr's separate putchar() for UART and Debug for speed.

README.md, ch32v003fun/ch32v003fun.h, minichlink/Makefile.macos, minichlink/README.md, minichlink/minichlink.c
Tested on a M1, but I haven't tried it on older Intel-based machines.
I turned off some warnings since the compiler spewed a lot of warnings which looks ugly. :) There's one warning still remaining, it's an easy fix but I didn't feel comfortable doing that since it might be a reason for the function DefaultWriteWord() to always return a hardcoded 0 instead of the ret -value.
```
minichlink.c:636:6: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
int ret = 0;
^
```
**-Wno-deprecated-non-prototype** takes care of warnings for main() 
**-Wno-deprecated-declarations** handlers a deprecation warning for kIOMasterPortDefault
**-Wno-asm-operand-widths** takes care of all the warnings below which I don't want to fix since it might affect the other architectures. @cnlohr …
=> Add support for macOS

minichlink/Makefile, minichlink/minichlink.c
I have tested the Makefile on MacOS and Linux. I assume it will still work on windows since that define is not changed.
=> Redo reverted patches for MacOS 

examples/systick_irq/README.md, examples/systick_irq/systick_irq.c
This PR modifies the SysTick IRQ example to work with the new SysTick usage in the ch32v003fun startup. Previously the SysTick counter was disabled by default but now it is initialized to run continuously which could cause spurious interrupts as this example starts up.
=> Updated for SysTick IRQ example for latest changes in ch32v003fun library.

examples/i2c_oled/README.md, examples/i2c_oled/i2c_oled.c, examples/i2c_oled/oled.h
This PR expands support of OLED display dimensions from the original 128x32 to include 128x64 and 64x32 types commonly available with the same SSD1306 controller. Display type is selectable at compile time with preprocessor macros and the demo code automatically adapts to utilize the full display area.
=> Support more types of OLED displays

ch32v003fun/ch32v003fun.h
When expression was passed to Delay_Ms unexpected macro expansion was happening. Fixed.
=> Allow expressions to be passed to Delay_Ms and Delay_Us.

examples/debugprintfdemo/.vscode/launch.json
Moved the flash command to deploySteps which makes it runs on restart.
=> Fix restarting vscode debugger

examples/hsitrim/Makefile, examples/hsitrim/hsitrim.c
This is an example of how to use the HSITRIM register to alter the internal high speed oscillator.  It displays the contents and meaning of the RCC->CTLR register.  It then enables the MSO on pin PC4 and sets the MSO source to the internal high speed oscillator.  It then enters a loop waiting for the characters ',' and '.' from the serial port (115200 baud) and correspondingly lowers or increases the HSITRIM value in the RCC->CTLR register.
=> Add hsitrim example

.gitignore, ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.mk, examples/cpp_virtual_methods/Makefile, examples/cpp_virtual_methods/README.md, examples/cpp_virtual_methods/cpp_virtual_methods.cpp, examples/cpp_virtual_methods/example.cpp, examples/cpp_virtual_methods/example.h
When using ch32v003fun with C++, there is an error when using virtual methods,
which is shown in the example program "cpp_virtual_methods" in the examples folder.
Without the usage of `__libc_init_array`, the virtual table of the class instance `Example` is not initialized correctly:
```
(gdb) info vtbl Example
vtable for 'ExampleClass' @ 0x0 (subobject @ 0x20000004):
[0]: 0x11e0006f
[1]: 0x0 <InterruptVectorDefault()>
```
In this case, a call to a virtual method will result to an invalid call and the program won't work as expected.
Here, the example program will only print out `Begin example`,
but does not print any values which are implemented in overridden virtual methods.
It seems like the MCU resets here.
In other environments like with my Arduino Core, the hard fault interrupt …
=> Fix error when using C++ virtual methods

ch32v003fun/ch32v003fun.h, examples/struct_direct_gpio/Makefile, examples/struct_direct_gpio/struct_direct_gpio.c, examples/struct_gpio/Makefile, examples/struct_gpio/debugprintfdemo.c, examples/struct_gpio/struct_gpio.c
this is a first attempt to do this for the gpio registers
are you generally interested in something like this?
do the names make sense?
To me this is easier to read than bitshifts but the enums are very verbose
structs are autogenerated here https://github.com/kabel42/ch32v003
=> make fields in (gpio) registers available via structs

.gitignore, README.md, build_scripts/README.md, build_scripts/build_all.cmd, build_scripts/build_all.sh, build_scripts/build_all_clangd.sh, build_scripts/clean_all.sh, build_scripts/clean_all_clangd.sh, ch32v003fun/ch32v003fun.mk
I figured out compatibility with clangd, I've added instructions to the main README.
Also I found the useful build_all.cmd, which now has siblings for linux, one of which will generate all the necessary compile_commands.yaml files so any project can be opened.
Through gitignore, no compile_commands.yaml will be committed (except if you wish), they are generated fine locally.
Intentionally didn't add compile_commands.yaml to makefile clean as its use is during writing.
Blink.bin is a remnant, probably from before the .gitignore was used.
___
moved the build_scripts
___
this time with clangd in the makefile, like suggested
___
had an adventure with git restoring the blink.bin
in case anyone ever needs to perform similar surgery on a branch
```
travel back one commit, keeping file changes …
```
=> added support for clangd #4

examples/i2c_slave/Makefile, examples/i2c_slave/README.md, examples/i2c_slave/i2c_slave.h, examples/i2c_slave/i2c_slave_example.c
This library and example show how to use the I2C peripheral in slave mode.
The library uses a one-byte address, allowing for up to 256 registers to be defined.
The first byte written to the device within a transaction determines the offset for following reads and writes, emulating a simple EEPROM.
The example will turn on a LED connected to PD0 when the LSB of register 0 is set to 1 and off when it's set to 0.
=> Add I2C slave library & example

examples/tim2_pwm/.gdbinit, examples/tim2_pwm/Makefile, examples/tim2_pwm/README.md, examples/tim2_pwm/debug.sh, examples/tim2_pwm/tim2_pwm.c
finally it works!!
I conceptually knew timer2 gets clock from APB1, but this line cost me HOURS to write: `	RCC->APB1PCENR |= RCC_APB1Periph_TIM2;`
=> timer2 pwm example

ch32v003fun/ch32v003fun.h
hope this is correct,
otherwise won't compile on arch-based linux
same fix as before (not me though)
=> add zicsr support to __enable_irq and __disable_irq

ch32v003fun/ch32v003fun.c
without clobers, this can break when compiler decides to reorder some immediates/addresses before the asm block (`SETUP_SYSTICK_HCLK` in this case)
=> use register clobbers in inline asm

.github/workflows/minichlink.yml, minichlink/Makefile
An extremely peculiar thing.
When the CI ubuntu-latest runner installs the MinGW toolchain for Windows, it somehow ends up with a version that has a default Windows Target of `_WIN32_WINNT = _WIN32_WINNT_WS03` (0x0502), that's "Windows Server 2003", one minor version after XP.
This activates a piece of block in `microgdbstub.h` that checks of `POLLIN` was defined or not, and tries to define these missing values, e.g. `#define POLLIN 0x0001`. The `winsock2.h` header only exposes the these macros when `_WIN32_WINNT >= 0x0600 (0x600 = Windows Vista)`, which in the CI build is not the case. I think the microgdbstub.h tries to "polyfill" in the missing values to try and still make use of it in these old Windows versions.
However, these compiled values are then **wrong** for the Windows 10 …
=> Fix minichlink Windows build

minichlink/minichlink.c, minichlink/minichlink.h, minichlink/pgm-wch-linke.c
I was playing around with writing to the Data0/1 fields in the Option Bytes and got myself into a situation where the chip was bricked - at least from a minichlink point of view.
When trying to flash I got this message that couldn't be fixed by a simple -u Unbrick.
```
Interface Setup
Fault writing memory (DMABSTRACTS = 08000302) (Execption executing Abstract Command) DMSTATUS: 004c0382
Fault on DefaultWriteWord Part 1
Fault writing memory (DMABSTRACTS = 08000302) (Execption executing Abstract Command) DMSTATUS: 004c0382
Fault on DefaultWriteWord Part 2
```
I could fix it with the WCH-LinkUtility and it turned out that I had enabled the Read Protection in my code.
The `usage()` function in minichlink had two commented-out lines for Read Protection, but no actual implementation so I added …
=> Add Enable/Disable Read Protection. Also rename Info -p to -i

minichlink/minichlink.c
The command for `Info` was hidden and used the -p flag. This PR renames it to `-i` (since -p would be used for Read Protection) , and adds it to the usage/help text.
It also shows all Option Bytes fields, not just the two first. The data is formatted as two %04x instead of a single %08x to improve readability.
I hope/assume that the change to -i won't clash with the same change made in my previous PR...
=> Add the Info-command for real and also show more output

ch32v003fun/ch32v003fun.h
Reverts cnlohr/ch32v003fun#163
Damn, I should've looked into the RM further, I thought the only two bits important here were the BIDIOE and the BIDIMODE turns out the RXONLY is the relevant bit here I guess (as it says in the name duh), so I was wrong, sorry
=> Revert "Fix SPI Direction"

minichlink/Makefile, minichlink/ardulink.c, minichlink/minichlink.c, minichlink/minichlink.h
I implemented a quick and dirty SWIO interface based on an Arduino Uno R3 board.
For the specific boards that I have, target reset logic seems to be required, so it was added as well.
Regards,
- Mark
=> Add an Arduino-based SWIO programmer

minichlink/minichlink.c, minichlink/pgm-wch-linke.c
+ remove round up in -r mode to read the requested amount of bytes
+ remove the 0x307 check and stash the old ReadBinaryBlob method
=> cleanup and simplify AH fix for ch32v307 read memory

ch32v003fun/ch32v003fun.c
SETUP_SYSTICK_HCLK can still break if static constructors dispatch will use those extra registers.
=> clobber all caller saved registers when calling an init_array

examples/GPIO/GPIO.c, extralibs/ch32v003_GPIO_branchless.h
To resolve "issues" [174](https://github.com/cnlohr/ch32v003fun/issues/174) and [172](https://github.com/cnlohr/ch32v003fun/issues/172) I'd like to present an even more **_disgusting_** GPIO library.
The GPIO port operations are a definite improvement, if not for writing to the port, then for applying the pin cfg to an entire port, much faster and slimmer than the old for loop iterating over all pins and doing a load-store each time.
For the single-parameter pin specifiers you requested:
First I tried variadic redirections due to unknowable ammount of parameters:
```
#define GPIO_pinMode(...)				GPIO_pinMode_(__VA_ARGS__)
#define GPIO_digitalWrite_hi(...)			GPIO_digitalWrite_hi_(__VA_ARGS__)
#define GPIO_digitalWrite_lo(...)			GPIO_digitalWrite_lo_(__VA_ARGS__)
#define …
```
=> GPIO port operations, single-parameter pin specifiers

examples/uartdemo/Makefile
```We don't do it that way anymore.  Check FUNCONF_USE_UARTPRINTF in your funconfig.h```
=> Remove CFLAGS switch for STDOUT_UART

ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.h
I tried running uartdemo, but it did not work because the baud rate was set directly on the BRR.
Since the CH32V003 has only one UART, I use the UART macro that was already there.
=> fix uart printf baud

ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.h, examples/sysclk_config/Makefile, examples/sysclk_config/funconfig.h, examples/sysclk_config/readme.md, examples/sysclk_config/sysclk_config.c
This PR is a result of a few days of testing and digging into the clock system on the CH32V003.  
- Wrong clock source for the PLL if the HSE is used.
- PA1 + PA2 reconfigured via AFIO to work with an xtal.
- leaves the HSI always on, which is required by the debug system to operate. It can be changed by changing one #define line.
**CSS  -Clock Security System** enabled. This allows a very easy unbricking (if normal way using programmer doesn't work) by shorting the PA1 (OSCI) to GND. HSE will fail, CSS will start the HSI and use it as sysclk source restoring the access via SWIO. The clock fail requires the NonMaskaleInterrrupt to clear the flag, otherwise it will end in the defaultHandler and an infinite loop. NMI IRQ has it's own declared alias handler which clears the flag. The user …
=> sysclk fixes and example project

attic/external_crystal_run_from_ram_turbo.c, ch32v003fun/ch32v003fun.h, examples/MCOtest/MCOtest.c, examples/MCOtest/funconfig.h, examples/bootload/bootload.c, examples/cpp_virtual_methods/cpp_virtual_methods.cpp, examples/dma_gpio/dma_gpio.c, examples/self_modify_code/self_modify_code.c, examples/spi_24L01_rx/nrf24l01_low_level.c, examples/spi_24L01_tx/nrf24l01_low_level.c, examples/standby_autowake/standby_autowake.c, examples/standby_btn/standby_btn.c, examples/ws2812bdemo/ws2812bdemo.c, extralibs/ch32v003_GPIO_branchless.h, extralibs/ch32v003_SPI.h
Remove the HSI/HSE footgun (if someone sets both values the chip ends up in a weird state)
Remove old SYSTEM_CORE_CLOCK `#defines`
Remove superfluous uses of APB_CLOCK
=> Clean up #define situation for SYSTEM_CORE_CLOCK, APB_CLOCK, USE_HSI/HSE

examples/adc_fixed_fs/Makefile, examples/adc_fixed_fs/README.md, examples/adc_fixed_fs/adc_fixed_fs.c, examples/adc_fixed_fs/funconfig.h
I used [https://github.com/hyOzd/serialplot](https://github.com/hyOzd/serialplot) to test the serial output. Works fine with 48 kHz and 2MBaud, but if serial output is not required or the signal is downsampled before transmission, it should operate at the maximum possible sampling rate of 1 MHz. Useful for software oversampling and other DSP stuff :)
=> Isochronous adc example

ch32v003fun/ch32v003fun.c
This patch will completely disable the SWDIO-based debug printf infrastructure when FUNCONF_USE_DEBUGPRINTF is set to zero. This allows printf() calls to be left in the project source without generating unwanted timeout delays when the debugger is not connected.
=> Disable DEBUGPRINTF I/O when FUNCONF_USE_DEBUGPRINTF = 0

minichlink/minichlink.c
fixes:
```
cd examples/bootload
make
which errors out with:
../../minichlink/minichlink -a -U -w bootload.bin bootloader -B                                                                     
Found WCH Link                                                                                                                      
WCH Programmer is LinkE version 2.9                                                                                                 
Chip Type: 003                                                                                                                      
Setup success                                                                                                                       
Flash Storage: 16 kB …
```
=> Update minichlink to not reset when writing bootloader.

examples/MCOtest/MCOtest.c, examples/MCOtest/funconfig.h, extralibs/ch32v003_SPI.h
1. MCO example enabled both HSI and HSE, fixed by disabling HSE in funconf.h and enabling it in the example code.
2. SPI library still requires APB_CLOCK to be defined, which was removed in #208
=> Issue #212 fixes - examples fail to compile

examples/i2c_oled/debug.sh, examples/spi_dac/debug.sh, examples/spi_oled/debug.sh, examples/tim1_pwm/debug.sh, examples/tim2_pwm/debug.sh
This PR removes several shell scripts that were inadvertently left in with example code when it was originally checked in. These scripts referred to external resources that are unlikely to be present for most users and should not be generally distributed.
=> Remove redundant debug shell scripts

examples/debugprintfdemo/debugprintfdemo.c
Avoid bricking CH32V003J4M6 by not using `PD4` in the demo.
=> Avoid bricking CH32V003J4M6 - For #219

examples/tim2_pwm/tim2_pwm.c
-Implement CH3 and CH4 optionally via #define
-By default only CH1 and CH2 are enabled.
-Channels 3 and 4 can be enabled by uncommenting the appropriate line -Choose whether default of PWM pins is HIGH (0xff) or LOW (0x00)
NOTES:
-Channel 3 is on a different port (GPIOC) which will be enabled if needed.
-Channel 4 is on the NRST pin so not usable unless you use `minichlink -d` to disable the NRST function so the pin can be used as a GPIO
-If your board has a bypass capacitor on PD7 for a reset button the waveforms observed on CH4 will not be nice square waves.
=> Add #ifdef support for CH3/CH4 in tim2_pwm example

examples/tim2_encoder/Makefile, examples/tim2_encoder/funconfig.h, examples/tim2_encoder/tim2_encoder.c
Uses partially remapped pins to read a rotary encoder (or any quadrature input) using pins that should be 5V tolerant
=> tim2_encoder example based on tim2_pwm_remap

examples/adc_fixed_fs/adc_fixed_fs.c
The ADC_ExternalTrigConv_T1_TRGO was written to the wrong register. It didn't cause problems in the example, but as soon as you try to change the trigger.
=> fix the adc trigger settings

extralibs/ch32v003_SPI.h
quite stupid mistakes, hope there aren't more of them hiding in the library :D
* SPI_begin_8() was not clearing the DFF bit of SPI1 CTRLR1 correctly
* SPI_transfer_16() had an 8bit return
Thanks to JKT in the discord for reporting (and suggestions on how to solve)
=> SPI lib: fixed bugs discovered by JKT

examples/direct_gpio/direct_gpio.c
count variable does not do anything
=> examples/direct gpio: remove count variable

minichlink/99-minichlink.rules, minichlink/minichlink.c
This fixes a typo preventing programmers to be specified on the command line. It also adds a udev rule for the rv003usb bootloader.
=> Fix typo preventing specpgm hint from being read on cmdline

ch32v003fun/ch32v003fun.mk
on arch linux, the risc compiler name is different. Add some logic to pick correct risc compiler on arch linux
=> fix compilation for arch linux

ch32v003fun/ch32v003fun.h
Simplifies UART_BRR register calculation. This is a fix for #271.
=> Simplify UART_BRR calculation

ch32v003fun/ch32v003fun.mk
Add the minichlink unbrick command to the makefile, such that the chip can be unbricked using 'make unbrick'.
=> Add minichlink unbrick to makefile

ch32v003fun/ch32v003fun.h
A tiny change but a very useful one if you want to use port B :smile:
=> Add GPIOB define for CH32V10x, CH32V20x and CH32V30x

ch32v003fun/ch32v003fun.mk, examples/cpp_virtual_methods/Makefile
This fixes compiler detection on Fedora 39 (gcc-riscv64-linux-gnu from the repo), which will no longer require compiling the entire gnu rv toolchain as described in the wiki. The repo provides `arm-none-eabi-newlib` for newlib, which places itself in a directory now properly checked by the makefile. **I have not tested this on a non-fedora system**
=> ch32v003fun.mk changes related to compiler prefix and newlib paths

examples/i2c_slave/README.md, examples/i2c_slave/i2c_slave.c, examples/i2c_slave/i2c_slave.h
- Correctly handles the stop event
- Supports reacting to a secondary I2C slave address (complete with it's own set of registers and callbacks)
- Support for chips other than the CH32V003 by removing the GPIO initialization from the library
Tested on CH32V003 and CH32V203.
=> Improve I2C slave library

minichlink/Makefile
Fixes the small problem left in the aftermath of https://github.com/cnlohr/ch32v003fun/pull/287
EDIT: more info in the man page, for example [here](https://manpages.ubuntu.com/manpages/xenial/man8/udevadm.8.html)
=> Fix udevadm using incorrect command

ch32v003fun/ch32v003fun.h
I redefined NVIC and SysTick with a `_BASE` definition for better compatibility with assembly. Otherwise one needs to define the `_BASE` defines in the application
=> define SysTick and NVIC via ***_BASE defs

minichlink/microgdbstub.h
This prevents a segfault when GDB connects to the server.
=> Fixes bad allocation GDB server.

.github/add_include.py, platformio.ini
Teeny tiny fix and extra comments. 
To make intellisense find the right include folder for `funconfig.h` not only during CI compilation, I also add the right path in `CPPPATH`, not as raw `CCFLAGS`.
Clarification for people wanting to upload via minichlink instead of OpenOCD were also made. With that, we get back the nice Intellisense in PlatformIO.
=> PlatformIO clarifications and Intellisense fix

minichlink/minichlink.c
On OSX, minichlink shows the warning 
> WARNING: You are not in the plugdev group, the canned udev rules will not work on your system
But udev does not exist on OSX, so this warning can be removed. I just extended the trick that makes it not appear on Windows either.
=> Remove plugdev warning on OSX

ch32v003fun/ch32v003fun.mk
To compare:
Before:
```
riscv64-unknown-elf-size tim1_pwm.elf
text       data        bss        dec        hex    filename
8784          0        448       9232       2410    tim1_pwm.elf
```
After:
```
Memory region         Used Size  Region Size  %age Used
FLASH:        8784 B        16 KB     53.61%
RAM:         448 B         2 KB     21.88%
```
=> Switch to -Wl,--print-memory-usage from elf-size

ch32v003fun/ch32v003fun.h
Added numbering to GPIOSpeed_TypeDef, for clarity and consistency
=> Make value of enum explicit

ch32v003fun/ch32v003fun.h
0x0104 is bitmask 100000100 which sets bit 2 (MSTR) and bit 8 (SSI). The latter has no relevance to master mode.
=> Fix bug where SSI is set by the SPI_Mode_Master mask

examples/dma_spi/Makefile, examples/dma_spi/README.md, examples/dma_spi/dma_spi.c, examples/dma_spi/funconfig.h
Implement SPI TX  using DMA, with 8-bit mode and soft NSS using a small state machine. This example prints the sequence of 0 .. 7 repeatedly.
=> Add example for using SPI TX with DMA on the CH32V003

ch32v003fun/ch32v003fun.mk
Useful for use in bigger non-makefile (cmake/meson) projects
=> Added target for object file

ch32v003fun/ch32v003fun.h
Noticed that a few defines where missing. This prevented the usage of TIM3 on my CH32X035
=> Support TIM3 on CH32X03x

examples_x035/tim3_pwm/Makefile, examples_x035/tim3_pwm/README.md, examples_x035/tim3_pwm/funconfig.h, examples_x035/tim3_pwm/tim3_pwm.c
Adds a PWM example for the general purpose TIM3 timer for the CH32X035.
=> Add TIM3 PWM example for CH32X035

examples/spi_oled/rand.h, examples/spi_oled/spi_oled.c
This change replaces the original LFSR code with a somewhat more efficient approach and pulls the function out into a separate header file that could be more easily used by others. It also adds two wrapper functions that emulate the behavior of the rand() and srand() functions from <stdlib.h>.
=> Break out random number generation to separate header

ch32v003fun/ch32v003fun.c
Fixes warnings:
```c
../../ch32v003fun/ch32v003fun.c: In function 'strstr':
../../ch32v003fun/ch32v003fun.c:374:13: warning: implicit declaration of function 'strchr' [-Wimplicit-function-declaration]
374 |         h = strchr(h, *n);
|             ^~~~~~
../../ch32v003fun/ch32v003fun.c:90:1: note: include '<string.h>' or provide a declaration of 'strchr'
89 | #include <ch32v003fun.h>
+++ |+#include <string.h>
90 | 
../../ch32v003fun/ch32v003fun.c:374:13: warning: incompatible implicit declaration of built-in function 'strchr' [-Wbuiltin-declaration-mismatch]
374 |         h = strchr(h, *n);
|             ^~~~~~
../../ch32v003fun/ch32v003fun.c:374:13: note: include '<string.h>' or provide a declaration of 'strchr'
```
=> Declare strchr before use

.github/workflows/build.yml, .github/workflows/minichlink.yml
Gets rid of all the warnings seen in e.g. https://github.com/cnlohr/ch32v003fun/actions/runs/10867336760 and adds a build for MacOs ARM64 too!
=> Update CI actions, build minichlink for MacOs ARM64 too

ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.h
`setjmp/longjmp` implementation for `rv32e` and `rv32ima`.
The standard `setjmp.h` that came with my toolchain defines `jmp_buf` with enough room for floating point registers as well. I did not add those registers because, as far as I can tell, support for floating point units is in the very early stages in the build tools.
I'm open to advice on how we could avoid including `setjmp.h` in `ch32v003fun.h`. That would allow us to define `jmp_buf` to not contain the space required for the floating point regs (saves 12*8 bytes of data).
=> Add setjmp/longjmp support

ch32v003fun/ch32v003fun.c
=> Fix interrupt vector constraint for new (>GCC13) compilers.

ch32v003fun/ch32v003fun.h, examples_v30x/check_memory_split/Makefile, examples_v30x/check_memory_split/check_memory_split.c, examples_v30x/check_memory_split/funconfig.h, extralibs/ch32v307gigabit.h, minichlink/minichlink.c, minichlink/minichlink.h, minichlink/pgm-wch-linke.c
This adds support for changing the amount of SRAM available in parts where the flash / SRAM split is configurable. Right now, this only works for the wch-linke adapter. The split is given as a command line flag and applied during the bulk memory write. Without this, the CH32V307 is limited to 32k of SRAM of a possible 128k. Adding this setting addresses issues #232, #280, and (in part) #303.
As referenced in issues #232, #280, and #303, some of the CH32V20x and  CH32V30x parts have a user configurable option trading flash size for user RAM size. As described by the CH32V307 datasheet (pg 4):
> The products with 256K FLASH+64K SRAM support user select word to be configured as one of several
combinations of (192K FLASH+128K SRAM), (224K FLASH+96K SRAM), (256K FLASH+64K SRAM),
(288K …
=> Configurable flash / ram split with minichlink

.github/add_include.py
Needed for e.g. rv003usb.S that expects that it can find funconfig.h. This repo does not yet have any example that uses assembly files that need an include from an example folder, this is prophylactic (and the correct behavior).
=> [PIO] Fix include path for assembly files

ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.h
From C11 onwards:
> The use of function declarators with empty parentheses (not prototype-format parameter type declarators) is an obsolescent feature.
```c
void foo(); // can be called with any arguments
void bar( void ); // can only be called with no arguments
```
=> Fix C functions that take any arguments

ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.h, examples/self_modify_code/self_modify_code.c
Added timeout in milliseconds argument and a return value to indicate weather timeout was reached.
Possible future enhancements:
- disable debug `printf` if timeout reached by default.
=> Add timeout to `WaitForDebuggerToAttach`

ch32v003fun/ch32v003fun.c
Fix for #424
New `InterruptVectorDefault()` definitions according to WCH's startup code examples.
=> Fix InterruptVectorDefault() for CH32V10x, CH32V20x and CH32V30x

minichlink/minichlink.c, minichlink/pgm-b003fun.c
``if( is_flash && memcmp( &eps->commandbuffer[60], blob, 1 ) ) goto verifyfail;`` I believe this should compare with respbuffer, otherwise it makes no sense.
``usleep(1000);`` before writing feature report so bootloader can process previous commands and minichlink doesn't throw error about retrying.
``if (eps->no_get_report) return r;`` so we don't wait to get feature report that will never come because bootloader finished working and usb connection throws ``ioctl (GFEATURE): No such device`` errors at us until timeout.
=> Fix USB bootloader programmer

ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.h, examples/debugprintfdemo/debugprintfdemo.c, examples/debugprintfdemo/funconfig.h
1. Make the default behavior on hard fault to wait forever, and then print the error.
2. Add DidDebuggerAttach().
3. Increase printf timeout, since it won't trigger if a debugger is not attached.
For printf:
1. Printf will wait up to 120ms at boot.
2. If printf has timed out, it will immediately continue.
3. If a debugger is reattached, it will keep printing.
4. If a debugger is attached, it will wait up to 120ms. Then continue at full speed.
=> Change printf behavior using a debugger present sentinel.

ch32v003fun/ch32v003fun.h
As discussed with Max and Cnlohr in Discord.
=> Add HPE support

minichlink/minichlink.c
Resume doesn't work for SysTick IRQ though.
=> Fixed halt/resume on WCH-LinkE

minichlink/pgm-wch-linke.c
If LE read or write command fails check internal state of programmer and chip id to determine if programmer was initialized in this run. If not, send magic command in hope to fix things. Works when you just plugged WCH-LinkE into the USB and running minichlink with command that skips startup.
=> Fix unitialized WCH-LinkE errors

examples_x035/uart_rx_tx_dma/Makefile, examples_x035/uart_rx_tx_dma/README.md, examples_x035/uart_rx_tx_dma/funconfig.h, examples_x035/uart_rx_tx_dma/uart_rx_tx_dma.c
Adds an example demonstrating efficient UART communication using DMA and IDLE line detection on the CH32X035 MCU.
The example utilizes DMA for data transfer and the UART's IDLE line detection feature to identify the end of a data packet.
=> [CH32X035] Add UART echo example with DMA and IDLE interrupts

minichlink/pgm-b003fun.c
Last time I added ``usleep`` in wrong place that caused flashing slowdown, this time I'm adding delay only on retries and also using ``DelayUs`` function that should work properly on Windows. Tested on linux and windows, and didn't see any performance penalty.
=> Deal with 'Issue with hid_send_feature_report' errors on linux

examples/tim1_pwm_complementary_outputs/.gdbinit, examples/tim1_pwm_complementary_outputs/Makefile, examples/tim1_pwm_complementary_outputs/README.md, examples/tim1_pwm_complementary_outputs/funconfig.h, examples/tim1_pwm_complementary_outputs/tim1_pwm_complementary_outputs.c, platformio.ini
This example shows how to set up Timer 1 (the Advanced Control Timer) to generate
Pulse-Width Modulation (PWM) with complementary outputs on two output pins.
This mode would be used, for example, to drive a motor with a H-bridge.
This program shows the effect of changing the PWM deadtime settings with complementary outputs.
=> Add TIM1 complementary outputs example

examples/tim1_pwm_complementary_outputs/tim1_pwm_complementary_outputs.c
I realized that there were now Arduino-style #defines for the PINs. This commit changes the pin initialization in my example to use them.
=> Modernize tim1_complementary_outputs example

minichlink/minichlink.c
Discovered by @monte-monte in https://github.com/cnlohr/ch32v003fun/compare/master...monte-monte:ch32v003fun:usb_terminal, looks like a clear bug.
Used when explicitly giving `./minichlink -C arduilink`
=> Fix copy-paste error in Ardulink init

ch32v003fun/ch32v003fun.h
Noticed that although the USAR(T)?_BASE constants where defined, the USAR(T)? constants weren't for the CH32X03x.
Verified USART3 on my CH32X035. The rest I haven't tested yet, but seems to match the reference manual.
Oh and the 4th UART peripheral is called USART4 on CH32X035, not UART4. Might be nice to fix that as well, but for now the extra USART peripherals are at least accessible with this PR.
=> Fix missing USART constants for CH32X03x

.gitignore, build_scripts/README.md, ch32v003fun/ch32v003fun.c, ch32v003fun/ch32v003fun.mk, examples/debugprintfdemo/.vscode/settings.json, examples/template/.vscode/settings.json
Set explicit `--compile-commands-dir` clangd argument in VS Code settings so that `compile_commands.json` will be used also for `ch32v003fun.c` which is outside the example directory.
Don't create `.clangd` files that filter out the `-march` and `-mabi` options. This is not necessary on recent clangd versions (I'm using 18), and the ABI has to be known to generate correct warnings. Additionally, that filter didn't work for files outside the current directory, similar the the first issue mentioned.
Finally, re-format the string handling functions that had clang complaining about empty `for` bodies.
The remaining warnings are due to two things: Firstly naked functions which contain C code. These would have to be re-written in assembly (at least a wrapper to call a C function), and I'm don't …
=> Fix some warnings from clangd in VS Code

ch32v003fun/ch32v003fun.h
Fix `__get_MEPC()` so that, like other CSR get/set helper functions, it enables `Zicsr` extension for GCC > 10.
Fixes:
- https://github.com/cnlohr/ch32v003fun/issues/483
=> Enable `Zicsr` in `__get_MEPC()`

ch32v003fun/ch32v003fun.h
This PR adds `__get_DEBUG_CR()` and `__set_DEBUG_CR()` functions to access the `DBGMCU_CR` CSR register in the CH32V003.
It also corrects the bit definitions for that register per the Reference Manual section 18.2.
=> CH32V003: Add accessors for DBGMCU_CR CSR register and correct its bit definitions.

examples/dma_gpio_ws2812/dma_gpio_ws2812.c
There was a stray pin call that wasn't using the gpio_pin variable in the dma_gpio_ws2812b example for the CH32V003.
=> replaced direct pin call with gpio variable

minichlink/ardulink.c
Hi !
This PR allows to actively poll an Ardulink device instead of waiting for the '!' character.
The poll is done using the '?' command, which returns a '+' character.
Submitting this because the tool I develop uses a bus pirate-like interface. Switching to ardulink mode requires the user quit the terminal to run minichlink, and the initial '!' usually gets lost.
I also thought about changing the serial port behavior in minichlink (using timeouts on serial reads), but this solution is simplier and works on the original ardulink as well.
=> minichlink: Active polling of Ardulink device

examples/tim1_phase_shifted_pwm/Makefile, examples/tim1_phase_shifted_pwm/README.md, examples/tim1_phase_shifted_pwm/funconfig.h, examples/tim1_phase_shifted_pwm/tim1_phase_shifted_pwm.c
This example shows how to use DMA with TIM1 to generate phase-shifted PWM outputs. This would be used with a full-bridge driver to generate controllable differential outputs over a wide range of duty cycles (vs. complementary PWM, which only produces up to 50% differential duty cycle)
=> Add example of using DMA for phase-shifted PWM outputs.

ch32fun/ch32x03xhw.h, examples_x035/exti_pin_change_isr/Makefile, examples_x035/exti_pin_change_isr/exti_pin_change_isr.c, examples_x035/exti_pin_change_isr/funconfig.h
Including a very simple example.
Somehow the reference does not match reality for the CH32X035 at least, as to select PC for an external interrupt the bits are b10, not b11 as described in the reference manual (same for PB, that's b01 instead of b10).
=> Add missing defines for EXTI on CH32X03x

ch32fun/ch32fun.c
Without these brackets gcc would fire an annoying warning when compile for ch32v208:
```
Compiling .pio/build/208_test/ch32v003fun/ch32fun/ch32fun.o
ch32v003fun/ch32fun/ch32fun.c: In function 'SystemInit':
ch32v003fun/ch32fun/ch32fun.c:1859:9: warning: this 'while' clause does not guard... [-Wmisleading-indentation]
1859 |         while(!(RCC->CTLR&RCC_HSERDY));
|         ^~~~~
In file included from ch32v003fun/ch32fun/ch32fun.h:348,
from ch32v003fun/ch32fun/ch32fun.c:93:
ch32v003fun/ch32fun/ch32v20xhw.h:1412:49: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'while'
1412 | #define RCC                                     ((RCC_TypeDef *)RCC_BASE)
|                                                 ^
ch32v003fun/ch32fun/ch32fun.c:1864:17: note: …
```
=> Add a {} guard to get rid of gcc warning when compile for ch32v208

minichlink/99-minichlink.rules, minichlink/README.md, minichlink/minichlink.c
From my understanding, udev should simply match the first available group, so specifying duplicates like this should not be a problem. However, a sed/envsubst solution might be better from a maintainer point of view. Tested and working on F41 (dialout), but needs a check on a plugdev system.
=> Udev rules and related documentation

.gitignore
seems like this was missed in #506
=> fix ch32fun directory reference in .gitignore.

README.md
I have created drivers for AHT20 and BMP280 sensors and tested it on one of my projects and would like to share it with community
https://github.com/pabloestrado/ch32fun-aht20-driver
https://github.com/pabloestrado/ch32fun-bmp280-driver
=> Add README links to BMP280 and AHT20 weather sensor drivers

ch32fun/ch32v30xhw.h
The problem I noticed in #498 was only partially solved by 5ec73e145b374778156b2ef0a5c99666ae95417c: there is still a condition checking only for ch32v20x before setting `PLL_MULTIPLICATION`.
As this file is only included when using a ch32v30x I just removed the check.
=> Fix PLL_MULTIPLICATION definition for ch32v303

ch32fun/ch32fun.c, ch32fun/ch32fun.h, ch32fun/ch32fun.ld, ch32fun/ch32fun.mk, ch32fun/ch59xhw.h, examples_ch59x/blink/Makefile, examples_ch59x/blink/blink.c, examples_ch59x/blink/funconfig.h, examples_ch59x/debugprintfdemo/Makefile, examples_ch59x/debugprintfdemo/debugprintfdemo.c, examples_ch59x/debugprintfdemo/funconfig.h
CH592/1 bringup and blinky. This is the start of CH59x support, and will conclude in merging the https://github.com/biemster/ch592_noblob_advertiser functionality in here.
One major issue is that the CH59x SDK is not based on structs like ch32, but just pointer #defines. Also I could not find anything resembling `RCC` in those #defines, so this might need some refactoring on both sides.
=> CH59x bringup and blinky

examples/gpio_and_adc/gpio_and_adc.c
Add additional notes regarding the external oscillator for the ch32v003 evaluation board.
Resolves #550.
=> Fix swapped `A0`/`A1` in `gpio_and_adc.c` example. 

ch32fun/ch59xhw.h, examples_ch59x/systick_irq/Makefile, examples_ch59x/systick_irq/funconfig.h, examples_ch59x/systick_irq/systick_irq.c
Example how to use SysTick on CH59x to generate periodic interrupts for timing.
=> CH59x SysTick IRQ example

ch32fun/ch32fun.c, ch32fun/ch59xhw.h, examples_ch59x/uartdemo/Makefile, examples_ch59x/uartdemo/funconfig.h, examples_ch59x/uartdemo/uartdemo.c
This example does `printf` on UART1 (rx,tx:PA8,PA9).
I #defined SetupUART like was done for ch32..., but I suspect that `_write` and `putchar` should be overloaded because of `WEAK`. I can change that easily if necessary.
Tested and working awesomely:
```bash
✔ ~/temp/CH570/ch32fun [ch59x-uartdemo L|✔] 
19:03 $ screen /dev/ttyUSB0 115200
ch32fun is awesome!
ch32fun is awesome!
ch32fun is aPA9 tx
PA9 tx
PA9 tx
PA9 tx
ch32fun is awesome!
ch32fun is awesome!
ch32fun
[screen is terminating]
✔ ~/temp/CH570/ch32fun [ch59x-uartdemo L|✔] 
19:04 $ 
```
Also there are a bit more #defines in ch59xhw.h than necessary, but UART1 was mentioned in the interrupt from sleep stuff that I will be working on next so I included the whole sleep mode related #defines.
=> CH59x UART1 printf and uartdemo example

ch32fun/ch32fun.c, examples_ch59x/uartdemo/uartdemo.c
For uart tx we should wait for the buffer to be empty so we don't risk overfilling it and dropping characters.
=> CH59x fix UART long printf issue #565

ch32fun/ch32fun.c
The current way `mstatus` being initialized prevents us from manipulation of `mtvec` register. If you want to make your own custom bootloader, you need to alter `mtvec` right after the bootloader loads your firmware.
For example, i have my booloader starting from `0x08000000`:
```c
#define MAIN_CODE_ADDR (0x400);
int main()
{ 
SystemInit();
doSomeBootloaderStuffHere();
void (*jump_func)(void) ;
jump_func = (void (*)(void))MAIN_CODE_ADDR;
jump_func(); 
}
```
Then my main firmware, which lives in `0x08000400`, takes control. The main firmware has its own startup code, so it tries to alter the mtvec register. If MCU is set to user mode in bootloader startup, i get a hardfault. If i initialize `mstatus` in the proposed way, everything works fine.
So my proposal is not to use user mode at all, …
=> [PROPOSAL] Set machine mode at startup

ch32fun/ch32v003hw.h, examples/exti_pin_change_isr/exti_pin_change_isr.c
Removed INFO_BASE
Removed CRC_TypeDef
Removed DEBUGMCU_STOP
Fixed ESIG_TypeDef to match RM and 00x correct names 
Fixed USART_TypeDef to match RM and 00x convert from 16bit to 32bit and remove reserved padding. 
Fixed WWDG_TypeDef to match RM and 00x convert from 32bit to 16bit and add reserved padding. 
Removed EXTEND_TypeDef
Remove all GPIO_ defines for bits 8 and higher. We only have 8 bit registers 0-7 
Fixed GPIO_ defines to be 32 bit fields to match RM and 00x 
Fixed AFIO_PCFR1register to properly name remapping fields (comments mostly) and remove unused defines for things we don't have 
Removed dualmod defines from ADC_CTLR1
removed ADC_TSVREFE from ADC_CTLR2
Changed ADC_STATR to 32 bit from 8 bit
Changed ADC_IOFRx to 32 bit from 16 bit and corrected mask from 0x0fff to 0x02ff …
=> Cleanup 003 with thing noticed when making 00x

minichlink/minichlink.c
Some tweaks for USB device selection. Now we are using ``-c`` option both for ardulink serial port and for vid/pid for b003boot. So I've made it clear which is which. And cleaned up console messages a bit.
=> Making console messages more coherent.

ch32fun/ch32v003hw.h
Copy and pasted the register description of each from each peripheral in the datasheet. This can and will make it easier to know what each register is/does without needing to check the datasheet each and every time
=> Added Register descriptions beside each peripherals struct

ch32fun/README.md, minichlink/minichlink.c, minichlink/pgm-wch-linke.c
This commit adds minichlink support for CH32L103.
I noticed that minichlink isn’t compatible with CH32V103 when using either WCH-LinkE (CH32V305) or WCH-Link (CH549), so I marked it as "Work in Progress." Did I miss anything?
=> Add minichlink support for L103

minichlink/minichlink.c, minichlink/minichlink.h, minichlink/pgm-b003fun.c
Presented changes are still guarded by ifdefs and will have effect only when compiled with ``TERMINAL_INPUT_BUFFER 1``.
- Fixed broken prints when incoming string had new lines anywhere inside of it but not at the end
- Fixed ``Send:`` label not showing until first terminal activity
- Added detection of ANSI compatibility of used terminal
- Fixed acking in ``b003boot`` terminal (not connected to the rest of the changes, but it's just a one line, didn't want to create a separate PR for it)
=> Improve buffered terminal in minichlink

examples_v20x/exti_blink/Makefile, examples_v20x/exti_blink/exti_blink.c, examples_v20x/exti_blink/funconfig.h
A short example that shows how to create an external interrupt for v20x devices. It uses the fun functions to configure the GPIOs.
=> add external interrupt blink example

ch32fun/ch57xhw.h, ch32fun/ch58xhw.h, ch32fun/ch59xhw.h, examples_ch5xx/RTC_irq/RTC_irq.c, examples_ch5xx/blink/blink.c, examples_ch5xx/debugprintfdemo/debugprintfdemo.c, examples_ch5xx/systick_irq/systick_irq.c, examples_ch5xx/uartdemo/uartdemo.c
While adding support for the ch5xx range one by one, I only added the parts of the SFR that were needed for the examples that were implemented. This change package will add the rest of the SFR pointer #defines so all the peripherals are accessible, even if they don't have an example in the `examples_ch5xx` folder.
=> CH5xx SFR completion

minichlink/Makefile, minichlink/minichlink.c, minichlink/minichlink.h, minichlink/pgm-wch-isp.c
This change package will enable `minichlink` to program chips using their builtin USB bootloader. This is mostly the ch5xx range, and enables only the `-w` write command (and `-b`) using the ISP interface. And the -E erase command.
I think this is really handy if one has to program a lot of new chips, since they don't need to separately enable the debug interface over USB and then flash the firmware, but can just immediately write the firmware.
This is also useful for people not owning a linkE (yet).
A future improvement will be the addition of `FUNCONF_USBDEBUGPRINTF`, which will get a feature to reboot the mcu into the internal bootloader so minichlink can be used like this without reconnecting the USB cable.
=> minichlink: builtin bootloader ISP programming

ch32fun/ch32fun.c, examples_usb/USBFS/usbfs_cdc_tty/Makefile, examples_usb/USBFS/usbfs_cdc_tty/README.md, examples_usb/USBFS/usbfs_cdc_tty/funconfig.h, examples_usb/USBFS/usbfs_cdc_tty/usb_config.h, examples_usb/USBFS/usbfs_cdc_tty/usbfs_cdc_tty.c, extralibs/fsusb.c
This demo shows a simple printf like behavior, but over USB CDC. It'll create a `/dev/ttyACM0` on linux (not sure what it does on windows), where one can monitor the messages and send simple commands.
=> USB CDC TTY and FUNCONF_USE_USBPRINTF

ch32fun/ch32v20xhw.h, ch32fun/ch57xhw.h, ch32fun/ch58xhw.h, ch32fun/ch59xhw.h, examples_ch5xx/README.md, examples_ch5xx/ble_beacon/Makefile, examples_ch5xx/ble_beacon/ble_beacon.c, examples_ch5xx/ble_beacon/funconfig.h, examples_ch5xx/iSLER/iSLER.c, extralibs/iSLER.h
This is an example of how to implement a simple low power BLE beacon with iSLER. While both low power and iSLER already worked on many chips, the issue was that after a low power state the RF would not properly wake up anymore.
This change package fixes that as well.
=> BLE beacon low power demo

ch32fun/ch58xhw.h, examples_ch5xx/README.md, examples_ch5xx/RTC_irq/RTC_irq.c, examples_ch5xx/ble_beacon/ble_beacon.c, examples_ch5xx/lowpower/lowpower.c, examples_ch5xx/systick_irq/systick_irq.c
The ch582 does not have the low power functions implemented yet, and thus can't to battery powered BLE beacon yet.
This package implements the RTC irq demo, low power demo and ble beacon demo for this chip, making it one of the best supported chips in the ch5xx line together with ch570/2 and ch59x.
=> Ch582 low power

minichlink/cmdserver.h
Use the `closesocket` instead of the `close`, thus conform to the `#define closesocket close` macro (line 23) to ensure that consistent socket closing processing is called across platforms.
=> minichlink: fix windows build

.github/workflows/build.yml
Per Discord request.
Now uses only one CI job to build all Makefile projects instead of the previous 101. Retains fast compile times by using `gnu parallel` to compile multiple Makefile projects at once. Uses 3 threads per Makefile project. Only takes about 36 seconds total.
PlatformIO CI remains untouched.
=> Build all Makefile projects in one job, but still multithreaded

examples_ch5xx/mcpy_demo/Makefile, examples_ch5xx/mcpy_demo/funconfig.h, examples_ch5xx/mcpy_demo/mcpy_demo.c
Newly found custom WCH instruction ``mcpy`` that supported in CH570/2 and CH585 chips. It greatly increases memory copying speed. But you need to respect 4 bytes alignment. Also it's probably copies in 4 bytes chunks.
=> Add mcpy demo for CH570/2 and CH585

.github/workflows/build.yml, .github/workflows/minichlink.yml, ch32fun/ch32fun.mk, misc/install_xpack_gcc.ps1
* Drops depedency on `$(shell expr '$(PREFIX)-gcc -dumpversion | cut -f1 -d.' \>= 13)` by using Make builtins like `firstword`, `filter` and `if` to achieve the same result
* Surpresses noisy Windows errors when executing `where` on non-installed programms, it would print `INFO: Could not find files for the given pattern(s).` over and over again. (Redirection of stderr to `nul` or `/dev/null` on Linux, leaving stdout intact)
* Adds a native Windows build job that compiles all ch32v003 examples in the `examples/` folder using `make` via `build_scripts/build_all.cmd`
* uses and thus also tests existing `install_xpack_gcc.ps1` script to install dependencies and setup environment
* small addition to detect Github runners and add it to the special `$GITHUB_ENV` environment variable too, …
=> Drop dependency on "expr", add Windows Makefile build to CI
